/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c FreecadDBusServer -a dbusserver.h:dbusserver.cpp org.freecad.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef DBUSSERVER_H_1355016641
#define DBUSSERVER_H_1355016641

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.freecad
 */
class FreecadDBusServer: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freecad")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freecad\">\n"
"    <method name=\"newDocument\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"docName\"/>\n"
"    </method>\n"
"    <method name=\"addBrep\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"objectName\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"data\"/>\n"
"    </method>\n"
"    <method name=\"disectBrep\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"objectName\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"data\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    FreecadDBusServer(QObject *parent);
    virtual ~FreecadDBusServer();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void addBrep(const QString &objectName, const QString &data);
    void disectBrep(const QString &objectName, const QString &data);
    void newDocument(const QString &docName);
Q_SIGNALS: // SIGNALS
};

#endif
